USE shakingdog;
SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE dog;
TRUNCATE TABLE relationship;
SET FOREIGN_KEY_CHECKS = 1;
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('A Wee Deoch an Doris with Nithdee', 'B', 4, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Absolute Iz Pesni Lovchiva', 'B', 4, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Adelia Is Velsa', 'B', 2, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Adeline Tuskulum', 'B', 5, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Aida Forest Soverin', 'B', 5, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Akenside Calypso', 'B', 4, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Akenside Electra', 'B', 4, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Akenside Eyebright at Lexmar', 'B', 4, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Akimbo’s Bom-Sicka-Bom', 'B', 4, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Akimbo’s Emil', 'D', 4, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Akimbo’s Ida', 'B', 2, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Alcumlow Azure', 'B', 4, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Alcumlow Heather', 'B', 4, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Alcumlow Miss Teeq', 'B', 4, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Alcumlow Mulberry', 'B', 4, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Alcumlow Parsley', 'D', 4, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Alcumlow Patience', 'B', 5, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Alcumlow Solitaire', 'D', 4, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Alcumlow Starry Night', 'B', 5, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Alderseadale Heart of Gold', 'B', 4, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Alderseadale Kiss the Stars', 'B', 5, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Alderseadale Like a Star', 'D', 5, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Alderseadale Lucky Star', 'D', 5, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Alderseadale Northern Star', 'D', 5, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Alderseadale Starry Eyed F', 'B', 5, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Alexis Bělohorský skřítek', 'B', 4, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Alisa Sly Fox', 'B', 5, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Allewelt´s Brezel', 'B', 2, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Allewelt´s Happy Tristan', 'D', 4, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Amble Dene Holly', 'B', 5, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Angliyskiy Gentleman Iz Lesnogo Kraya', 'D', 2, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Annesuz Incognito', 'B', 5, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Annesuz New Horizon at Glen Mara', 'D', 5, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Annesuz No Publicity', 'D', 5, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Annesuz Under the Raidar', 'B', 5, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Annesuz Under Wraps', 'D', 5, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Aprils Blessing', 'B', 2, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Ara Rumcajsowe Obejście', 'B', 5, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Ardenforest Lindy Lee', 'B', 5, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Ardenforest Thumbalina at Moleschamber', 'B', 4, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Arjaybe Red Squall', 'B', 4, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Arnika Scrato', 'B', 4, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Art Hunter Bohemia', 'D', 4, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Badgerbeck Pablo', 'D', 4, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Badgerholme Epsom Jet', 'D', 4, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Bannerkin''s Best Dressed at Bordysk', 'B', 4, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Beaconpike Red Saturn', 'D', 4, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Beaconpike Stargazer at Bordurrock', 'B', 5, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Bohunt Aussie Maid for Ommiks', 'B', 4, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Bohunt Boomerang for Ewoks', 'D', 4, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Bohunt Boy A Born 21 Sept 2013', 'D', 1, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Bohunt Boy B Born 21 Sept 2013 M Bohunt Serial Thriller Cedarhill Irresistabelle', 'D', 1, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Bohunt Boy C Born 21 Sept 2013 M Bohunt Serial Thriller Cedarhill Irresistabelle', 'D', 1, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Bohunt Devil in a Blue Dress', 'B', 5, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Bohunt Dot Net', 'D', 4, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Bohunt Foreign Affair with Otterpond', 'D', 4, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Bohunt Girl D Born 21 Sept 2013', 'B', 1, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Bohunt Hoi Polloi', 'B', 5, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Bohunt Hue And Cry', 'D', 5, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Bohunt Kiss My Pixel', 'B', 4, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Bohunt Mover and Shaker', 'D', 2, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Bohunt Pillow Fight', 'D', 5, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Bohunt Pistols at Dawn', 'D', 4, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Bohunt Scarlett Ribbonz', 'B', 5, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Bohunt Serial Thriller', 'D', 2, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Bohunt Small Talk', 'B', 5, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Bohunt The Witch is Back', 'B', 4, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Bohunt Tit for Tat', 'B', 5, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Bohunt Waltzing Matilda', 'B', 4, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Boldwind Kiera', 'B', 5, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Boldwind Naturally', 'D', 4, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Boldwind Winter Solstrice', 'B', 4, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Bombax Chess Queen', 'B', 4, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Bombax Coque Rouge', 'D', 5, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Bombax Lumumba', 'B', 4, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Bombax Qubec', 'D', 5, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Bombax Queen Viktoria', 'B', 5, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Bombax Ragna', 'B', 5, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Bon Appetit by Tythrop', 'B', 4, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Bonnie of Falcons Lake', 'B', 5, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Boomtown Ace of Hearts', 'B', 5, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Boomtown Ace of Spades', 'D', 5, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Boomtown Strawberry Fields', 'B', 5, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Borderby''s American Bluemaestro', 'D', 5, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Borderby''s Nitty Gritty', 'D', 4, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Borderby''s Pride And Prejudice', 'D', 5, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Bordergrand Ailton', 'D', 4, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Borderhouse Bettini Scott', 'D', 5, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Borderhouse Ernest Hemmingway', 'D', 5, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Borderigg Rewind To Ravenside', 'B', 4, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Borderoba Baroness', 'B', 5, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Borderoba Busy Bee', 'B', 5, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Borderoba Fantasy at Fleret', 'B', 4, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Borderstable Heavenly Angel', 'B', 5, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Borderstable Heavenly Beauty', 'B', 5, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Borderstable Heavenly Devil', 'D', 5, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Borderstable Heavenly Dream', 'D', 4, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Borderworld Beauty Queen', 'B', 4, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Borderxpress Miss Moppet', 'B', 5, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Borderxpress Miss Parsley', 'B', 4, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Borderxpress Miss Potter', 'B', 4, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Bordirus Brevis Venator', 'B', 5, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Bordirus Meretrix', 'B', 4, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Bordour Galway Girl', 'B', 5, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Bordour I''m-Just-A CuppaTea', 'B', 2, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Bordour I''m-just-a Espresso', 'B', 4, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Bordour It''s a wind up', 'B', 4, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Bordour Kick the Dust Up', 'B', 5, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Bordour My Sorta Gift', 'B', 4, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Bordour Shape of You', 'D', 5, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Bordour Sofia the first', 'B', 5, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Bordour Southern Gentleman', 'D', 5, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Bordour Talk it up', 'D', 4, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Bordurrock Rainbow Rising', 'D', 4, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Bordurroock Shoot to Thrill', 'B', 4, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Bordysk’s America Arctic Fox', 'B', 5, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Bordysk’s American March Brown', 'D', 5, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Bordysk’s Baby Doll', 'B', 5, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Bordysk’s California Mosquito', 'D', 5, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Bordysk’s Deep Diver', 'D', 5, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Bordysk’s Dog Nibbler', 'D', 5, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Bordysk’s Gipsy King', 'D', 5, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Bordysk’s Great Lakes Krystal Stone', 'B', 5, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Bordysk’s Peter Ross', 'D', 4, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Bordysk''s Hot Spot', 'B', 4, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Bordysk''s Myrdogg', 'B', 5, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Borrowa Dazzler', 'D', 5, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Brumberhill Benchmarked', 'D', 4, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Brumberhill Blue Sky', 'B', 5, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Brumberhill Blue Tempest', 'D', 4, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Bubbles Fleret Moravia', 'D', 4, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Car z Polešovic', 'D', 5, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Cedarhill Irresistabelle', 'B', 3, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Cedarhill Legally Blonde', 'B', 5, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Cedarhill No Excuse Needed', 'D', 4, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Chorbeck Chatty Man JW ShCM', 'D', 4, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Chytrugh Lord Mangu Forest', 'D', 4, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Clipstone Sail Away', 'B', 4, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Croalchapel Miss Ellie', 'B', 5, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Duncan von der Borderranch', 'D', 4, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Dunrobin I''m-Just-a Toby Jug', 'D', 4, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Earthdog Lanyard by Beaconpike', 'D', 5, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Eiska is Velsa', 'B', 5, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Farmway Harrier', 'D', 5, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Fehmarn Roddys Hope', 'D', 5, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Germanus Red Skipper', 'D', 5, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Glen Mara Half Way to heaven', 'B', 4, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Hawcoat Lord George', 'D', 5, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Hellas Gem Stone', 'B', 4, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Irton Up Helly Aa', 'D', 4, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Jondia Litter Cracker', 'D', 5, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Kenquince Neap Tide', 'B', 5, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Kersfell Sea the Stars at Annesuz', 'B', 4, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Lovely Lotte von der Border Meute', 'B', 4, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Mansergh Song Thrush', 'D', 4, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Maryvics New Release', 'B', 5, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Maustrappe''s Force of Nature', 'D', 4, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Merlin Von Den Torfmoorseen', 'D', 5, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Mishka Mariner', 'B', 4, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Neil Fleret Moravia', 'D', 2, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Ottercap Sunshine Superman', 'D', 5, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Otterpond Stamped with Bohunt', 'B', 5, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Oxcroft Route to Borderxpress', 'B', 4, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Quarryway Dill', 'D', 5, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Ragatam Rumour at Alderseadale', 'B', 4, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Raleniro Brand New Age', 'D', 2, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Ravenside Ballymoss', 'D', 4, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Ravenside Rumours About Caldewgate', 'D', 4, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Rockamore Filippa K', 'B', 5, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Rosey Rebel', 'B', 5, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Ruffpups Five Star At Boldwind', 'B', 5, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Sagimus Trick', 'D', 4, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Skyline Johnny come lately', 'D', 5, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Solitary Mist', 'D', 4, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Stella Rover Antey', 'D', 4, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Sweeping Slow Fox', 'D', 4, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Toftahill GAME ON', 'D', 4, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Toftahill Inside Out', 'D', 3, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Tythrop Tap On Wood For Ravenside', 'D', 5, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Tythrop Tapas', 'D', 4, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Wendy z Plešného jezera', 'B', 5, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Willowhatton Turpin', 'D', 5, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Wintergarden Fly High By Plushcourt', 'D', 4, 4, 0, 0);
INSERT INTO dog (name, gender, shakingdogstatusid, cecsstatusid, shakingdoginferoverride, cecsinferoverride) VALUES ('Xtra Tale of the Whiskered Gentry', 'B', 5, 4, 0, 0);
INSERT INTO relationship (sireid, damid, childid) VALUES (179, 139, 1);
INSERT INTO relationship (sireid, damid, childid) VALUES (135, 5, 2);
INSERT INTO relationship (sireid, damid, childid) VALUES (160, 143, 3);
INSERT INTO relationship (sireid, damid, childid) VALUES (44, 147, 4);
INSERT INTO relationship (sireid, damid, childid) VALUES (131, 134, 6);
INSERT INTO relationship (sireid, damid, childid) VALUES (174, 134, 7);
INSERT INTO relationship (sireid, damid, childid) VALUES (174, 134, 8);
INSERT INTO relationship (sireid, damid, childid) VALUES (158, 11, 9);
INSERT INTO relationship (sireid, damid, childid) VALUES (178, 169, 10);
INSERT INTO relationship (sireid, damid, childid) VALUES (178, 169, 11);
INSERT INTO relationship (sireid, damid, childid) VALUES (155, 17, 12);
INSERT INTO relationship (sireid, damid, childid) VALUES (16, 14, 13);
INSERT INTO relationship (sireid, damid, childid) VALUES (148, 19, 14);
INSERT INTO relationship (sireid, damid, childid) VALUES (148, 19, 15);
INSERT INTO relationship (sireid, damid, childid) VALUES (155, 17, 16);
INSERT INTO relationship (sireid, damid, childid) VALUES (128, 19, 18);
INSERT INTO relationship (sireid, damid, childid) VALUES (136, 20, 23);
INSERT INTO relationship (sireid, damid, childid) VALUES (166, 165, 20);
INSERT INTO relationship (sireid, damid, childid) VALUES (136, 20, 21);
INSERT INTO relationship (sireid, damid, childid) VALUES (136, 20, 22);
INSERT INTO relationship (sireid, damid, childid) VALUES (136, 20, 24);
INSERT INTO relationship (sireid, damid, childid) VALUES (136, 20, 25);
INSERT INTO relationship (sireid, damid, childid) VALUES (146, 181, 26);
INSERT INTO relationship (sireid, damid, childid) VALUES (88, 184, 28);
INSERT INTO relationship (sireid, damid, childid) VALUES (172, 28, 29);
INSERT INTO relationship (sireid, damid, childid) VALUES (47, 159, 30);
INSERT INTO relationship (sireid, damid, childid) VALUES (145, 156, 31);
INSERT INTO relationship (sireid, damid, childid) VALUES (128, 153, 32);
INSERT INTO relationship (sireid, damid, childid) VALUES (183, 32, 33);
INSERT INTO relationship (sireid, damid, childid) VALUES (128, 153, 34);
INSERT INTO relationship (sireid, damid, childid) VALUES (128, 153, 35);
INSERT INTO relationship (sireid, damid, childid) VALUES (128, 153, 36);
INSERT INTO relationship (sireid, damid, childid) VALUES (151, 152, 37);
INSERT INTO relationship (sireid, damid, childid) VALUES (182, 39, 40);
INSERT INTO relationship (sireid, damid, childid) VALUES (130, 170, 41);
INSERT INTO relationship (sireid, damid, childid) VALUES (89, 38, 42);
INSERT INTO relationship (sireid, damid, childid) VALUES (132, 91, 43);
INSERT INTO relationship (sireid, damid, childid) VALUES (62, 54, 49);
INSERT INTO relationship (sireid, damid, childid) VALUES (65, 162, 50);
INSERT INTO relationship (sireid, damid, childid) VALUES (65, 133, 51);
INSERT INTO relationship (sireid, damid, childid) VALUES (65, 133, 52);
INSERT INTO relationship (sireid, damid, childid) VALUES (65, 133, 53);
INSERT INTO relationship (sireid, damid, childid) VALUES (62, 58, 55);
INSERT INTO relationship (sireid, damid, childid) VALUES (127, 83, 56);
INSERT INTO relationship (sireid, damid, childid) VALUES (65, 133, 57);
INSERT INTO relationship (sireid, damid, childid) VALUES (62, 162, 60);
INSERT INTO relationship (sireid, damid, childid) VALUES (65, 133, 61);
INSERT INTO relationship (sireid, damid, childid) VALUES (61, 68, 63);
INSERT INTO relationship (sireid, damid, childid) VALUES (82, 64, 65);
INSERT INTO relationship (sireid, damid, childid) VALUES (59, 60, 67);
INSERT INTO relationship (sireid, damid, childid) VALUES (62, 83, 69);
INSERT INTO relationship (sireid, damid, childid) VALUES (144, 70, 71);
INSERT INTO relationship (sireid, damid, childid) VALUES (71, 171, 72);
INSERT INTO relationship (sireid, damid, childid) VALUES (76, 78, 73);
INSERT INTO relationship (sireid, damid, childid) VALUES (74, 77, 75);
INSERT INTO relationship (sireid, damid, childid) VALUES (180, 129, 79);
INSERT INTO relationship (sireid, damid, childid) VALUES (140, 149, 80);
INSERT INTO relationship (sireid, damid, childid) VALUES (84, 138, 85);
INSERT INTO relationship (sireid, damid, childid) VALUES (175, 27, 87);
INSERT INTO relationship (sireid, damid, childid) VALUES (168, 99, 90);
INSERT INTO relationship (sireid, damid, childid) VALUES (45, 138, 86);
INSERT INTO relationship (sireid, damid, childid) VALUES (164, 92, 93);
INSERT INTO relationship (sireid, damid, childid) VALUES (177, 42, 94);
INSERT INTO relationship (sireid, damid, childid) VALUES (177, 42, 95);
INSERT INTO relationship (sireid, damid, childid) VALUES (177, 42, 96);
INSERT INTO relationship (sireid, damid, childid) VALUES (177, 42, 97);
INSERT INTO relationship (sireid, damid, childid) VALUES (176, 154, 98);
INSERT INTO relationship (sireid, damid, childid) VALUES (183, 163, 100);
INSERT INTO relationship (sireid, damid, childid) VALUES (167, 163, 101);
INSERT INTO relationship (sireid, damid, childid) VALUES (161, 102, 103);
INSERT INTO relationship (sireid, damid, childid) VALUES (113, 106, 104);
INSERT INTO relationship (sireid, damid, childid) VALUES (141, 81, 105);
INSERT INTO relationship (sireid, damid, childid) VALUES (141, 81, 106);
INSERT INTO relationship (sireid, damid, childid) VALUES (137, 81, 107);
INSERT INTO relationship (sireid, damid, childid) VALUES (141, 107, 108);
INSERT INTO relationship (sireid, damid, childid) VALUES (141, 111, 109);
INSERT INTO relationship (sireid, damid, childid) VALUES (113, 106, 110);
INSERT INTO relationship (sireid, damid, childid) VALUES (141, 107, 112);
INSERT INTO relationship (sireid, damid, childid) VALUES (173, 66, 113);
INSERT INTO relationship (sireid, damid, childid) VALUES (142, 48, 114);
INSERT INTO relationship (sireid, damid, childid) VALUES (150, 48, 115);
INSERT INTO relationship (sireid, damid, childid) VALUES (157, 46, 116);
INSERT INTO relationship (sireid, damid, childid) VALUES (157, 46, 117);
INSERT INTO relationship (sireid, damid, childid) VALUES (157, 125, 118);
INSERT INTO relationship (sireid, damid, childid) VALUES (157, 46, 119);
INSERT INTO relationship (sireid, damid, childid) VALUES (157, 125, 120);
INSERT INTO relationship (sireid, damid, childid) VALUES (157, 125, 121);
INSERT INTO relationship (sireid, damid, childid) VALUES (157, 125, 122);
INSERT INTO relationship (sireid, damid, childid) VALUES (157, 46, 123);
INSERT INTO relationship (sireid, damid, childid) VALUES (178, 126, 124);
